"""CI check: verify requirements.txt is in sync with pyproject.toml.

Usage:  uv run python tools/check_requirements.py
Exit 0 on match, 1 on drift (with diff written to stderr).

This script writes the generated requirements to a temp file to avoid
polluting the working directory (no stray file artefacts).
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "requirements.txt"
PYPROJECT = ROOT / "pyproject.toml"


def _normalize(content: str) -> str:
    """Strip the two-line uv autogeneration header for stable comparison."""
    lines = content.splitlines()
    if len(lines) >= 2 and lines[0].startswith("# This file was autogenerated"):
        return "\n".join(lines[2:]).strip()
    return content.strip()


def main() -> int:
    if not PYPROJECT.is_file():
        print(f"ERROR: {PYPROJECT} not found", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_req = Path(tmpdir) / "requirements.txt"

        result = subprocess.run(
            [
                "uv", "pip", "compile", str(PYPROJECT),
                "--extra", "a2ui-http",
                "-o", str(tmp_req),
            ],
            capture_output=True,
            text=True,
            cwd=str(ROOT),
        )

        if result.returncode != 0:
            print(f"ERROR: uv pip compile failed:\n{result.stderr}", file=sys.stderr)
            return 1

        generated = tmp_req.read_text(encoding="utf-8").strip()
        current = REQUIREMENTS.read_text(encoding="utf-8").strip() if REQUIREMENTS.is_file() else ""

        generated_norm = _normalize(generated)
        current_norm = _normalize(current)

        if generated_norm != current_norm:
            print("ERROR: requirements.txt is out of sync with pyproject.toml", file=sys.stderr)
            print("", file=sys.stderr)
            print("Run: uv pip compile pyproject.toml --extra a2ui-http -o requirements.txt", file=sys.stderr)
            print("", file=sys.stderr)

            import difflib
            diff = difflib.unified_diff(
                current_norm.splitlines(keepends=True),
                generated_norm.splitlines(keepends=True),
                fromfile="requirements.txt (current)",
                tofile="requirements.txt (expected from pyproject.toml)",
            )
            sys.stderr.writelines(diff)
            return 1

    print("requirements.txt matches pyproject.toml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
